spring.application.name=db_subastas

# Configuración del Driver de conexión
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuración de Hibernate para auto-crear tablas
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Configuracion de variables
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}

# JWT Configuration
jwt.secret=${JWT_SECRET:ClaveSecretaSuperSeguraYDeAlMenos256BitsParaHS256}
jwt.expiration-ms=3600000